apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traffic-monitor
  namespace: kube-system
  labels:
    app: traffic-monitor
    component: network-monitoring
spec:
  selector:
    matchLabels:
      app: traffic-monitor
  template:
    metadata:
      labels:
        app: traffic-monitor
        component: network-monitoring
    spec:
      # Run on every node
      hostNetwork: true
      hostPID: true
      
      # Privileged mode for packet capture (in production, use specific capabilities)
      containers:
      - name: traffic-monitor
        image: traffic-monitor:v10
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_RAW
              - NET_ADMIN
              - SYS_ADMIN
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OUTPUT_FILE
          value: "/tmp/endpoints.json"
        volumeMounts:
        - name: endpoints-data
          mountPath: /tmp
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: endpoints-data
        hostPath:
          path: /tmp/traffic-monitor
          type: DirectoryOrCreate
      # Tolerations to run on all nodes including master
      tolerations:
      - operator: Exists
        effect: NoSchedule
